backend:
  name: github
  repo: opensites/govsites.io
  branch: main
  base_url: https://us-central1-sonorous-shore-313203.cloudfunctions.net # The base URL for your Firebase Function
  auth_endpoint: /oauth/auth # The path to the OAuth endpoint of the function
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Dogs"
            name: "dogs"
            widget: object
            fields:
              - label: "Breeds"
                name: "breeds"
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "markdown",
                    }
              - label: "Size"
                name: "size"
                widget: "string"
